<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>TableTool.Cli</RootNamespace>
    <AssemblyName>TableTool.Cli</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.102.1" />
    <PackageReference Include="YamlDotNet" Version="15.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TableTool.Runtime\TableTool.Runtime.csproj" />
  </ItemGroup>

</Project>
