namespace TableTool.Runtime;

/// <summary>
/// Template placeholder for the generated Tables.cs file.
/// The actual Tables.cs is auto-generated by the TableTool.Cli build tool.
/// This file exists only for compilation reference.
/// </summary>
public static class TablesTemplate
{
    /// <summary>Directory where JSON data files are located. Set this at app startup.</summary>
    public static string DataPath { get; set; } = "./data";

    /// <summary>Load all tables eagerly. Override in generated Tables.cs.</summary>
    public static void LoadAll()
    {
        // Generated code will override this
    }
}
