using System.Text;
using TableTool.Cli.Schema.Models;

namespace TableTool.Cli.CodeGen;

/// <summary>Generates C# record classes and table classes for each table definition.</summary>
public sealed class CSharpClassGenerator
{
    private readonly string _namespace;

    public CSharpClassGenerator(string ns = "GameConfig")
    {
        _namespace = ns;
    }

    /// <summary>Generate C# code for a single table (record + table classes).</summary>
    public string Generate(TableDefinition table, List<EnumDefinition> enums)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// ============================================================");
        sb.AppendLine("// Auto-generated by TableTool. DO NOT EDIT.");
        sb.AppendLine($"// Source: {table.File}");
        sb.AppendLine("// ============================================================");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {_namespace}");
        sb.AppendLine("{");

        // Generate inline struct types first (if any)
        var structNames = new Dictionary<string, List<FieldDefinition>>();
        foreach (var field in table.Fields)
        {
            if (field.ParsedStructType != null && field.ParsedStructType.StructFields != null)
            {
                var structName = GetStructClassName(field.Name);
                structNames[field.Name] = field.ParsedStructType.StructFields;
                GenerateStructClass(sb, structName, field.ParsedStructType.StructFields, 1);
            }
        }

        // Generate record class
        var recordName = GetRecordClassName(table.Name);
        sb.AppendLine($"    /// <summary>{table.Description ?? table.Name} record</summary>");
        sb.AppendLine($"    public sealed class {recordName}");
        sb.AppendLine("    {");

        foreach (var field in table.Fields)
        {
            var csharpType = GetCSharpType(field, structNames);
            var defaultValue = GetDefaultValue(field);
            var isCustom = field.ParsedType?.Kind == FieldTypeKind.Custom;

            sb.AppendLine($"        /// <summary>{field.Comment ?? field.Name}</summary>");
            if (isCustom && field.ParsedType?.CustomTypeName != null)
                sb.AppendLine($"        [JsonConverter(typeof({field.ParsedType.CustomTypeName}Converter))]");
            sb.AppendLine("        [JsonInclude]");
            sb.AppendLine($"        public {csharpType} {field.Name} {{ get; private set; }} = {defaultValue};");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate key struct for composite PK
        var pkFields = table.GetPrimaryKeyFields();
        var isComposite = pkFields.Count > 1;
        string keyType;

        if (isComposite)
        {
            keyType = $"{table.Name}Key";
            GenerateCompositeKeyStruct(sb, table, keyType, 1);
        }
        else if (pkFields.Count == 1)
        {
            var pkField = table.Fields.Find(f => f.Name == pkFields[0]);
            keyType = GetCSharpPrimitiveType(pkField?.ParsedType);
        }
        else
        {
            keyType = "string";
        }

        // Generate table class
        var tableClassName = GetTableClassName(table.Name);
        var recordType = recordName;
        sb.AppendLine($"    /// <summary>{table.Description ?? table.Name} table</summary>");
        sb.AppendLine($"    public sealed class {tableClassName} : IDataTable<{keyType}, {recordType}>");
        sb.AppendLine("    {");

        // Internal data store
        sb.AppendLine($"        private Dictionary<{keyType}, {recordType}> _data = new();");
        sb.AppendLine();

        // Get method
        sb.AppendLine($"        public {recordType} Get({keyType} key) =>");
        sb.AppendLine($"            _data.TryGetValue(key, out var v) ? v : throw new KeyNotFoundException($\"Key '{{key}}' not found in {table.Name}Table.\");");
        sb.AppendLine();

        // TryGet method
        sb.AppendLine($"        public {recordType}? TryGet({keyType} key) =>");
        sb.AppendLine($"            _data.TryGetValue(key, out var v) ? v : null;");
        sb.AppendLine();

        // ContainsKey method
        sb.AppendLine($"        public bool ContainsKey({keyType} key) => _data.ContainsKey(key);");
        sb.AppendLine();

        // GetAll method
        sb.AppendLine($"        public IReadOnlyCollection<{recordType}> GetAll() => _data.Values;");
        sb.AppendLine();

        // GetAllKeys method
        sb.AppendLine($"        public IReadOnlyCollection<{keyType}> GetAllKeys() => _data.Keys;");
        sb.AppendLine();

        // Count property
        sb.AppendLine($"        public int Count => _data.Count;");
        sb.AppendLine();

        // GetEnumerator
        sb.AppendLine($"        public IEnumerator<{recordType}> GetEnumerator() => _data.Values.GetEnumerator();");
        sb.AppendLine();

        // Load method (called by DataLoader)
        sb.AppendLine("        [Obsolete(\"Internal use only. Called by DataLoader.\")]");
        sb.AppendLine($"        internal void Load(Dictionary<{keyType}, {recordType}> data)");
        sb.AppendLine("        {");
        sb.AppendLine("            _data = data;");
        sb.AppendLine("        }");

        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private void GenerateStructClass(StringBuilder sb, string className, List<FieldDefinition> fields, int indent)
    {
        var ind = new string(' ', indent * 4);
        sb.AppendLine($"{ind}/// <summary>Inline struct for {className}</summary>");
        sb.AppendLine($"{ind}public sealed class {className}");
        sb.AppendLine($"{ind}{{");

        foreach (var field in fields)
        {
            var csharpType = GetCSharpPrimitiveType(field.ParsedType);
            var defaultValue = GetDefaultValue(field);
            sb.AppendLine($"{ind}    [JsonInclude]");
            sb.AppendLine($"{ind}    public {csharpType} {field.Name} {{ get; private set; }} = {defaultValue};");
            sb.AppendLine();
        }

        sb.AppendLine($"{ind}}}");
        sb.AppendLine();
    }

    private void GenerateCompositeKeyStruct(StringBuilder sb, TableDefinition table, string keyType, int indent)
    {
        var ind = new string(' ', indent * 4);
        var pkFields = table.GetPrimaryKeyFields();

        sb.AppendLine($"{ind}/// <summary>Composite primary key for {table.Name}</summary>");
        sb.AppendLine($"{ind}public readonly struct {keyType} : IEquatable<{keyType}>");
        sb.AppendLine($"{ind}{{");

        // Fields and constructor
        foreach (var pkFieldName in pkFields)
        {
            var field = table.Fields.Find(f => f.Name == pkFieldName);
            var csType = GetCSharpPrimitiveType(field?.ParsedType);
            sb.AppendLine($"{ind}    public readonly {csType} {pkFieldName};");
        }
        sb.AppendLine();

        // Constructor
        sb.AppendLine($"{ind}    public {keyType}(");
        for (int i = 0; i < pkFields.Count; i++)
        {
            var field = table.Fields.Find(f => f.Name == pkFields[i]);
            var csType = GetCSharpPrimitiveType(field?.ParsedType);
            sb.Append($"{ind}        {csType} {ToCamelCase(pkFields[i])}");
            sb.AppendLine(i < pkFields.Count - 1 ? "," : ")");
        }
        sb.AppendLine($"{ind}    {{");
        foreach (var pkFieldName in pkFields)
        {
            sb.AppendLine($"{ind}        {pkFieldName} = {ToCamelCase(pkFieldName)};");
        }
        sb.AppendLine($"{ind}    }}");
        sb.AppendLine();

        // Equals
        sb.AppendLine($"{ind}    public bool Equals({keyType} other) =>");
        var eqConditions = pkFields.Select(f => $"{f} == other.{f}");
        sb.AppendLine($"{ind}        {string.Join(" &&" + Environment.NewLine + "        ", eqConditions)};");
        sb.AppendLine();

        // GetHashCode
        sb.AppendLine($"{ind}    public override int GetHashCode()");
        sb.AppendLine($"{ind}    {{");
        sb.AppendLine($"{ind}        var hash = new HashCode();");
        foreach (var pkFieldName in pkFields)
        {
            sb.AppendLine($"{ind}        hash.Add({pkFieldName});");
        }
        sb.AppendLine($"{ind}        return hash.ToHashCode();");
        sb.AppendLine($"{ind}    }}");
        sb.AppendLine();

        // == and != operators
        sb.AppendLine($"{ind}    public static bool operator ==({keyType} left, {keyType} right) => left.Equals(right);");
        sb.AppendLine($"{ind}    public static bool operator !=({keyType} left, {keyType} right) => !left.Equals(right);");
        sb.AppendLine();

        // ToString
        sb.AppendLine($"{ind}    public override string ToString() => $\"({string.Join(", ", pkFields.Select(f => $"{{{f}}}"))})\";");
        sb.AppendLine();

        // Equals(object)
        sb.AppendLine($"{ind}    public override bool Equals(object? obj) => obj is {keyType} other && Equals(other);");

        sb.AppendLine($"{ind}}}");
        sb.AppendLine();

        // MakeKey static helper on record class
        var recordName = GetRecordClassName(table.Name);
    }

    private static string GetCSharpType(FieldDefinition field, Dictionary<string, List<FieldDefinition>> structNames)
    {
        // Direct struct
        if (field.ParsedStructType != null && field.ParsedStructType.StructFields != null)
        {
            // If wrapped in List (list<struct>), use List<StructName>
            if (field.ParsedType?.Kind == FieldTypeKind.List && field.ParsedType.ElementType?.Kind == FieldTypeKind.Struct)
                return $"List<{GetStructClassName(field.Name)}>";
            return GetStructClassName(field.Name);
        }

        return GetCSharpPrimitiveType(field.ParsedType);
    }

    private static string GetCSharpPrimitiveType(FieldType? fieldType)
    {
        if (fieldType == null) return "object";
        return fieldType.Kind switch
        {
            FieldTypeKind.Bool => "bool",
            FieldTypeKind.Int => "int",
            FieldTypeKind.Long => "long",
            FieldTypeKind.Float => "float",
            FieldTypeKind.String => "string",
            FieldTypeKind.List when fieldType.ElementType != null => $"List<{GetCSharpPrimitiveType(fieldType.ElementType)}>",
            FieldTypeKind.Map when fieldType.KeyType != null && fieldType.ValueType != null =>
                $"Dictionary<{GetCSharpPrimitiveType(fieldType.KeyType)},{GetCSharpPrimitiveType(fieldType.ValueType)}>",
            FieldTypeKind.Enum => fieldType.EnumName ?? "string",
            FieldTypeKind.Custom => fieldType.CustomDefinition?.CSharp ?? fieldType.CustomTypeName ?? "object",
            FieldTypeKind.Struct => "object",
            _ => "object"
        };
    }

    private static string GetDefaultValue(FieldDefinition field)
    {
        if (field.ParsedType?.Kind == FieldTypeKind.List)
            return "new()";

        if (field.ParsedStructType != null && field.ParsedStructType.StructFields != null)
            return "null!";

        if (field.ParsedType == null) return "default!";

        if (field.ParsedType.Kind == FieldTypeKind.Custom && field.ParsedType.CustomDefinition?.CSharp != null)
        {
            var csType = field.ParsedType.CustomDefinition.CSharp;
            if (csType == "string") return "string.Empty";
            if (csType.Contains("DateTime")) return "default";
            if (csType.Contains("Vector")) return "default";
            return "default!";
        }

        return field.ParsedType.Kind switch
        {
            FieldTypeKind.Bool => "false",
            FieldTypeKind.Int => "0",
            FieldTypeKind.Long => "0L",
            FieldTypeKind.Float => "0f",
            FieldTypeKind.String => "string.Empty",
            FieldTypeKind.List => "new()",
            FieldTypeKind.Map => "new()",
            FieldTypeKind.Struct => "null!",
            FieldTypeKind.Enum => "default",
            _ => "default!"
        };
    }

    internal static string GetRecordClassName(string tableName) => $"{tableName}Record";
    internal static string GetTableClassName(string tableName) => $"{tableName}Table";
    internal static string GetStructClassName(string fieldName) => $"{fieldName}Struct";

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }
}
