using System.Text;
using TableTool.Cli.Schema.Models;

namespace TableTool.Cli.CodeGen;

/// <summary>Generates the Tables.cs static access root.</summary>
public sealed class TablesGenerator
{
    private readonly string _namespace;

    public TablesGenerator(string ns = "GameConfig")
    {
        _namespace = ns;
    }

    /// <summary>Generate the Tables.cs code.</summary>
    public string Generate(List<TableDefinition> tables, List<EnumDefinition> enums,
        List<CustomTypeDefinition>? customTypes = null)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// ============================================================");
        sb.AppendLine("// Auto-generated by TableTool. DO NOT EDIT.");
        sb.AppendLine("// ============================================================");
        sb.AppendLine();
        var usings = new HashSet<string> { "System", "System.Collections.Generic",
            "System.IO", "System.Text.Json", "System.Text.Json.Serialization" };

        // Add custom type imports
        if (customTypes != null)
        {
            foreach (var ct in customTypes)
            {
                if (ct.Import != null)
                    foreach (var imp in ct.Import)
                        usings.Add(imp);
            }
        }

        foreach (var u in usings.OrderBy(x => x))
            sb.AppendLine($"using {u};");
        sb.AppendLine();
        sb.AppendLine($"namespace {_namespace}");
        sb.AppendLine("{");

        // Inline IDataTable interface (self-contained, no external dependency)
        sb.AppendLine("    /// <summary>Generic interface for a typed data table.</summary>");
        sb.AppendLine("    public interface IDataTable<TKey, TRecord>");
        sb.AppendLine("        where TKey : notnull");
        sb.AppendLine("        where TRecord : class");
        sb.AppendLine("    {");
        sb.AppendLine("        TRecord Get(TKey key);");
        sb.AppendLine("        TRecord? TryGet(TKey key);");
        sb.AppendLine("        bool ContainsKey(TKey key);");
        sb.AppendLine("        IReadOnlyCollection<TRecord> GetAll();");
        sb.AppendLine("        IReadOnlyCollection<TKey> GetAllKeys();");
        sb.AppendLine("        int Count { get; }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate custom type converters
        GenerateCustomTypeConverters(sb, customTypes);

        GenerateDataLoaderClass(sb, tables);
        sb.AppendLine();

        // Tables static class
        sb.AppendLine("    /// <summary>Static access point for all game configuration tables.</summary>");
        sb.AppendLine("    public static class Tables");
        sb.AppendLine("    {");
        sb.AppendLine("        private static DataLoader _loader = new();");
        sb.AppendLine("        private static bool _loaded;");
        sb.AppendLine();

        // Lazy properties for each table
        foreach (var table in tables)
        {
            var pkFields = table.GetPrimaryKeyFields();
            string keyType;
            if (table.IsListMode)
            {
                keyType = "string";
            }
            else if (pkFields.Count > 1)
            {
                keyType = $"{table.Name}Key";
            }
            else
            {
                var pkField = table.Fields.Find(f => f.Name == pkFields[0]);
                keyType = pkField?.ParsedType?.ToCSharpType() ?? "string";
            }

            var tableClassName = CSharpClassGenerator.GetTableClassName(table.Name);
            var recordClassName = CSharpClassGenerator.GetRecordClassName(table.Name);

            sb.AppendLine($"        private static Lazy<{tableClassName}> _{ToCamelCase(table.Name)} = new(() => _loader.Load<{tableClassName}, {keyType}, {recordClassName}>(\"{table.Name}\"));");
            sb.AppendLine();
        }

        // Public accessors
        foreach (var table in tables)
        {
            var tableClassName = CSharpClassGenerator.GetTableClassName(table.Name);
            sb.AppendLine($"        public static {tableClassName} {table.Name} => _{ToCamelCase(table.Name)}.Value;");
        }

        sb.AppendLine();
        sb.AppendLine("        /// <summary>Directory where JSON data files are located.</summary>");
        sb.AppendLine("        public static string DataPath");
        sb.AppendLine("        {");
        sb.AppendLine("            get => _loader.DataPath;");
        sb.AppendLine("            set => _loader.DataPath = value;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Load settings from TableSettings (auto on first access).</summary>");
        sb.AppendLine("        static Tables()");
        sb.AppendLine("        {");
        sb.AppendLine("            _loader.DataPath = TableSettings.DataPath;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // LoadAll method
        sb.AppendLine("        /// <summary>Load all tables eagerly.</summary>");
        sb.AppendLine("        public static void LoadAll()");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_loaded) return;");
        foreach (var table in tables)
        {
            sb.AppendLine($"            _ = {table.Name};");
        }
        sb.AppendLine("            _loaded = true;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // ReloadAll method
        sb.AppendLine("        /// <summary>Reload all tables.</summary>");
        sb.AppendLine("        public static void ReloadAll()");
        sb.AppendLine("        {");
        foreach (var table in tables)
        {
            sb.AppendLine($"            _{ToCamelCase(table.Name)} = new(() => _loader.Load<{CSharpClassGenerator.GetTableClassName(table.Name)}, {GetKeyType(table)}, {CSharpClassGenerator.GetRecordClassName(table.Name)}>(\"{table.Name}\"));");
        }
        sb.AppendLine("            _loaded = false;");
        sb.AppendLine("            LoadAll();");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private void GenerateCustomTypeConverters(StringBuilder sb, List<CustomTypeDefinition>? customTypes)
    {
        if (customTypes == null || customTypes.Count == 0) return;

        foreach (var ct in customTypes)
        {
            var storageType = ct.Storage;
            var csharpType = ct.CSharp;
            var parseExpr = ct.Parse ?? $"{csharpType}.Parse({{0}})";

            sb.AppendLine($"    /// <summary>JsonConverter for custom type {ct.Name} (storage: {storageType}, csharp: {csharpType})</summary>");
            sb.AppendLine($"    internal class {ct.Name}Converter : JsonConverter<{csharpType}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public override {csharpType} Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)");
            sb.AppendLine("        {");
            if (storageType == "string")
            {
                sb.AppendLine("            var str = reader.GetString();");
                sb.AppendLine($"            return {parseExpr.Replace("{0}", "str")};");
            }
            else if (storageType == "int" || storageType == "long")
            {
                sb.AppendLine($"            var val = reader.Get{storageType[0].ToString().ToUpper() + storageType.Substring(1)}();");
                sb.AppendLine($"            return {parseExpr.Replace("{0}", "val")};");
            }
            else
            {
                sb.AppendLine($"            // Fallback: read as {storageType}");
                sb.AppendLine($"            var str = reader.GetString();");
                sb.AppendLine($"            return {parseExpr.Replace("{0}", "str")};");
            }
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine($"        public override void Write(Utf8JsonWriter writer, {csharpType} value, JsonSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteStringValue(value.ToString());");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
    }

    private void GenerateDataLoaderClass(StringBuilder sb, List<TableDefinition> tables)
    {
        sb.AppendLine("    /// <summary>Handles deserialization of JSON data files into table classes.</summary>");
        sb.AppendLine("    internal class DataLoader");
        sb.AppendLine("    {");
        sb.AppendLine("        public string DataPath { get; set; } = \"./data\";");
        sb.AppendLine();

        sb.AppendLine("        public TTable Load<TTable, TKey, TRecord>(string name)");
        sb.AppendLine("            where TTable : class, new()");
        sb.AppendLine("            where TKey : notnull");
        sb.AppendLine("            where TRecord : class");
        sb.AppendLine("        {");
        sb.AppendLine("            var jsonPath = Path.Combine(DataPath, $\"{name}.json\");");
        sb.AppendLine("            if (!File.Exists(jsonPath))");
        sb.AppendLine("                throw new FileNotFoundException($\"Data file not found: {jsonPath}\");");
        sb.AppendLine();
        sb.AppendLine("            var json = File.ReadAllText(jsonPath);");
        sb.AppendLine("            using var doc = JsonDocument.Parse(json);");
        sb.AppendLine("            var root = doc.RootElement;");
        sb.AppendLine();
        sb.AppendLine("            // Handle both record-map format and list format");
        sb.AppendLine("            var recordsProp = root.GetProperty(\"records\");");
        sb.AppendLine("            var table = new TTable();");
        sb.AppendLine();
        sb.AppendLine("            // Get the Load method via reflection");
        sb.AppendLine("            var loadMethod = typeof(TTable).GetMethod(\"Load\",");
        sb.AppendLine("                System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);");
        sb.AppendLine();
        sb.AppendLine("            if (loadMethod == null)");
        sb.AppendLine("                throw new InvalidOperationException($\"Table {name} does not have a Load method.\");");
        sb.AppendLine();
        sb.AppendLine("            if (root.TryGetProperty(\"isList\", out var isList) && isList.GetBoolean())");
        sb.AppendLine("            {");
        sb.AppendLine("                // Array format");
        sb.AppendLine("                var records = JsonSerializer.Deserialize<List<TRecord>>(recordsProp.GetRawText())!;");
        sb.AppendLine("                var dict = new Dictionary<string, TRecord>();");
        sb.AppendLine("                for (int i = 0; i < records.Count; i++)");
        sb.AppendLine("                    dict[i.ToString()] = records[i];");
        sb.AppendLine("                loadMethod.Invoke(table, new object[] { dict });");
        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine("                // Record map format");
        sb.AppendLine("                var records = JsonSerializer.Deserialize<Dictionary<TKey, TRecord>>(recordsProp.GetRawText())!;");
        sb.AppendLine("                loadMethod.Invoke(table, new object[] { records! });");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return table;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static string GetKeyType(TableDefinition table)
    {
        var pkFields = table.GetPrimaryKeyFields();
        if (table.IsListMode) return "string";
        if (pkFields.Count > 1) return $"{table.Name}Key";
        var pkField = table.Fields.Find(f => f.Name == pkFields[0]);
        return pkField?.ParsedType?.ToCSharpType() ?? "string";
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    /// <summary>Generate TableSettings.cs (only created once, user edits DataPath freely).</summary>
    public string GenerateSettings(string ns)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// ============================================================");
        sb.AppendLine("// Auto-generated by TableTool. Edit DataPath to match your project.");
        sb.AppendLine("// This file is only created once and won't be overwritten.");
        sb.AppendLine("// ============================================================");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Runtime configuration for table data loading.</summary>");
        sb.AppendLine("    public static class TableSettings");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Path to JSON data files (relative or absolute).</summary>");
        sb.AppendLine("        public static string DataPath = \"./data\";");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
